# Shell variables
# Generated by 'wal'
wallpaper='/home/js-bro/.config/hypr/Wallpaper/arch.png'

# Special
background='#12121b'
foreground='#bcd4ea'
cursor='#bcd4ea'

# Colors
color0='#12121b'
color1='#56708E'
color2='#607F9F'
color3='#698CAF'
color4='#759DC3'
color5='#7BA5CD'
color6='#83B1DA'
color7='#bcd4ea'
color8='#8394a3'
color9='#56708E'
color10='#607F9F'
color11='#698CAF'
color12='#759DC3'
color13='#7BA5CD'
color14='#83B1DA'
color15='#bcd4ea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
